name: finances
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  money2: ^4.0.0
  syncfusion_flutter_charts: ^24.2.7+1
  file_selector: ^1.0.3
  path_provider: ^2.1.2
  thumbnailer: ^2.2.0
  mime: ^1.0.5
  material_symbols_icons: ^4.2719.3
  collection: ^1.18.0
  uri_to_file: ^1.0.0
  flutter_tesseract_ocr: ^0.4.24
  pdfx: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: ^1.24.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tessdata/
