name: finances
description: A new Flutter project.
publish_to: 'none'
version: 0.2.1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: 1.18.0
  fc_native_image_resize: 0.10.0
  file_selector: 1.0.3
  fl_chart: 0.69.0
  flex_color_picker: 3.5.1
  flutter_expandable_fab: 2.3.0
  flutter_iconpicker: 4.0.0
  google_mlkit_text_recognition: 0.13.1
  grouped_list: 6.0.0
  intl: 0.19.0
  logger: 2.4.0
  material_symbols_icons: 4.2785.1
  money2: 5.2.1
  path: 1.9.0
  path_provider: 2.1.4
  permission_handler: 11.3.1
  photo_view: 0.15.0
  quick_actions: 1.0.7
  shared_preferences: 2.3.2
  sqflite: 2.3.3+1
  sqflite_common_ffi: 2.3.3
  uri_to_file: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
