name: finances
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  money2: ^4.0.0
  file_selector: ^1.0.3
  path_provider: ^2.1.2
  material_symbols_icons: ^4.2719.3
  collection: ^1.18.0
  uri_to_file: ^1.0.0
  flutter_tesseract_ocr: ^0.4.24
  photo_view: ^0.15.0
  fl_chart: ^0.67.0
  intl: ^0.19.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3
  http: ^1.2.1
  fpdart: ^1.1.0
  url_launcher: ^6.2.6
  image_pixels: ^3.0.2
  logger: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: ^1.24.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tessdata/
