name: finances
description: A new Flutter project.
publish_to: 'none'
version: 0.6.1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: 1.19.0
  fc_native_image_resize: ^0.13.0
  file_selector: 1.0.3
  fl_chart: ^0.69.2
  flex_color_picker: ^3.6.0
  flutter_expandable_fab: 2.3.0
  flutter_iconpicker: ^4.0.1
  google_mlkit_text_recognition: ^0.14.0
  grouped_list: 6.0.0
  intl: 0.19.0
  logger: ^2.5.0
  material_symbols_icons: ^4.2801.0
  money2: ^5.4.6
  path: 1.9.0
  path_provider: ^2.1.5
  permission_handler: 11.3.1
  photo_view: 0.15.0
  quick_actions: ^1.1.0
  shared_preferences: ^2.3.4
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  sqlite3_flutter_libs: 0.5.28

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
