name: finances
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  money2: ^5.0.1
  file_selector: ^1.0.3
  path_provider: ^2.1.3
  material_symbols_icons: ^4.2741.0
  collection: ^1.18.0
  uri_to_file: ^1.0.0
  photo_view: ^0.15.0
  fl_chart: ^0.69.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  logger: ^2.2.0
  google_mlkit_text_recognition: ^0.13.0
  path: ^1.9.0
  fc_native_image_resize: ^0.10.0
  grouped_list: ^6.0.0
  flex_color_picker: ^3.4.1
  flutter_iconpicker: 4.0.0
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  permission_handler: ^11.3.1
  flutter_expandable_fab:
    git: https://github.com/programotuojes/flutter_expandable_fab

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
