name: Build releases

on:
  push:
    tags:
      - '**'

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Run tests
        run: nix develop -c -- flutter test

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=upload" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      - name: Build
        run: nix develop -c -- flutter build apk --split-per-abi --no-tree-shake-icons

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error

  release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    needs: [android, linux]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: generate-changelog.sh
          sparse-checkout-cone-mode: false
          fetch-depth: 0 # Needed for previous tags

      - name: Generate release notes
        run: ./generate-changelog.sh | tee changelog.md

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Rename artifacts
        run: |
           mv android/app-arm64-v8a-release.apk android/Finances.arm64-v8a.apk
           mv android/app-armeabi-v7a-release.apk android/Finances.armeabi-v7a.apk
           mv android/app-x86_64-release.apk android/Finances.x86_64.apk

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ github.ref_name }}" \
            -F changelog.md \
            android/Finances.arm64-v8a.apk \
            android/Finances.armeabi-v7a.apk \
            android/Finances.x86_64.apk
